config/routes.rb
MapSale::Application.routes.draw do
  root :to => "home#index"
  resources :companies
  resources :shops do
    collection do
      get :event_new
      post :event_create
    end
    member do
      get :event_new
    end
  end
  resources :shop_categories
  resources :shop_detail_types
  resources :districts
  resources :events
  
  namespace :api do
    post "/where", :controller => :search, :action => "now_where"
    get  "/where", :controller => :search, :action => "now_where"
    get  "/practice", :controller => :search, :action => "practice"
  end  
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :shop
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
    @shops = Shop.all
    @shop_data = Hash[@shops.map {|t| [t.id, name: t.name ]}]
  end

  def show
  end

  # GET /events/new
  def new
    @shops = Shop.all
    @shop_data = Hash[@shops.map {|t| [t.name, t.id ]}]
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
    @shops = Shop.all
    @shop_data = Hash[@shops.map {|t| [t.name, t.id ]}]
  end

  
  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:shop_id, :title, :summary, :dicount_conde, :start_time, :end_time)
    end
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this shop from being saved:</h2>
      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    ショップ名<br>
    <%= f.select :shop_id, @shop_data %>
  </div>
  <div class="field">
    タイトル<br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    説明<br>
    <%= f.text_area :summary %>
  </div>
  <div class="field">
    割引コード<br>
    <%= f.text_field :discount_code %>
  </div>
  <section id="eventForm">
  <div class="field">
    開始時刻<br>
    <%= f.datetime_select :start_time, :use_month_numbers => true %>
  </div>
  <div class="field">
    終了時刻<br>
    <%= f.datetime_select :end_time,  :use_month_numbers => true%>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
  </section>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>イベント</h1>

<table class="table">
  <thead>
    <tr>
      <th>No.</th>
      <th>ショップ名</th>
      <th>イベント名</th>
      <th colspan="3">編集</th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
	<td><%= event.id%></td>
        <td><%= @shop_data[event.shop_id][:name] %></td>
	<td><%= event.title %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Shop</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>イベント</strong>
  <%= @event.title %>
</p>
<p>
  <strong>説明</strong>
  <%= @event.summary %>
</p>
<p>
  <strong>割引コード</strong>
  <%= @event.discount_code %>
</p>
<p>
  <strong>開始時刻</strong>
  <%= @event.start_time %>
</p>
<p>
  <strong>終了時刻</strong>
  <%= @event.end_time %>
</p>




<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>