config/routes.rb
MapSale::Application.routes.draw do
  root :to => "home#index"
  resources :companies
  resources :shops do
    collection do
      get :event_new
      post :event_create
    end
    member do
      get :event_new
    end
  end
  resources :shop_categories
  resources :shop_detail_types
  resources :districts
  resources :events
  
  namespace :api do
    post "/where", :controller => :search, :action => "now_where"
    get  "/where", :controller => :search, :action => "now_where"
    get  "/practice", :controller => :search, :action => "practice"
  end  
end

app/models/district.rb
class District < ActiveRecord::Base
  has_many :shops


  def self.create_sql_search_name(arr)
    sql = Array.new
    arr.each do |e|
      sql.push(self.search(:district_name_cont => e).result.to_sql)
    end
    sql
  end


end

app/controllers/districts_controller.rb
class DistrictsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]

  # GET /shops
  # GET /shops.json
  def index
    @districts = District.all
  end

  def show
  end

  # GET /shops/new
  def new
    @district = District.new
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops
  # POST /shops.json
  def create
    @district = District.new(shop_params)

    respond_to do |format|
      if @district.save
        format.html { redirect_to @district, notice: 'District was successfully created.' }
        format.json { render action: 'show', status: :created, location: @district }
      else
        format.html { render action: 'new' }
        format.json { render json: @district.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    respond_to do |format|
      if @district.update(shop_params)
        format.html { redirect_to @district, notice: 'District was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @district.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @district.destroy
    respond_to do |format|
      format.html { redirect_to shops_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @district = District.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_params
      params.require(:district).permit(:prefecture, :disrict_name)
    end
end

app/views/districts/_form.html.erb
<%= form_for(@district) do |f| %>
  <% if @district.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@district.errors.count, "error") %> prohibited this shop from being saved:</h2>

      <ul>
      <% @district.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    都道府県<br>
    <%= f.select :prefecture, Company::PREFECTURES.map{|zone| [zone[1], zone[0] ]} %>
  </div>
   <div class="field">
    地域<br>
    <%= f.text_field :district_name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/districts/edit.html.erb
<h1>Editing company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/districts/index.html.erb
<h1>地域</h1>

<table class="table">
  <thead>
    <tr>
      <th>No.</th>
      <th>都道府県</th>
      <th>地域</th>
      <th colspan="3">編集</th>
    </tr>
  </thead>

  <tbody>
    <% @districts.each do |district| %>
      <tr>
	<td><%= district.id%></td>
	<td><%= Company::PREFECTURES[district.prefecture.to_s] %></td>
        <td><%= district.district_name %></td>
        <td><%= link_to 'Show', district %></td>
        <td><%= link_to 'Edit', edit_district_path(district) %></td>
        <td><%= link_to 'Destroy', district, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New District', new_district_path %>

app/views/districts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>地域</strong>
  <%= @district.district_name %>
</p>

<%= link_to 'Edit', edit_district_path(@district) %> |
<%= link_to 'Back', districts_path %>