config/routes.rb
MapSale::Application.routes.draw do
  root :to => "home#index"
  resources :companies
  resources :shops do
    collection do
      get :event_new
      post :event_create
    end
    member do
      get :event_new
    end
  end
  resources :shop_categories
  resources :shop_detail_types
  resources :districts
  resources :events
  
  namespace :api do
    post "/where", :controller => :search, :action => "now_where"
    get  "/where", :controller => :search, :action => "now_where"
    get  "/practice", :controller => :search, :action => "practice"
  end  
end

app/controllers/shop_detail_types_controller.rb
class ShopDetailTypesController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]

  # GET /shops
  # GET /shops.json
  def index
    @shop_detail_types = ShopDetailType.all
    @shop_category = ShopCategory.all
    @hash = @shop_category.map{ |i| [i.id, i.type_name]}.flatten

  end

  def show
  end

  # GET /shops/new
  def new
    @shop_detail_type = ShopDetailType.new
    @shop_category = ShopCategory.all
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop_detail_type = ShopDetailType.new(shop_detail_params)

    respond_to do |format|
      if @shop_detail_type.save
        format.html { redirect_to @shop_detail_type, notice: 'ShopDetailType was successfully created.' }
        format.json { render action: 'show', status: :created, location: @shop_detail_type }
      else
        format.html { render action: 'new' }
        format.json { render json: @shop_detail_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    respond_to do |format|
      if @shop_detail_type.update(shop_detail_params)
        format.html { redirect_to @shop_detail_type, notice: 'ShopDetailType was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @shop_detail_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop_detail_type.destroy
    respond_to do |format|
      format.html { redirect_to shops_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop_detail_type = ShopDetailType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_detail_params
      params.require(:shop_detail_type).permit(:shop_category_id, :detail_tag_name)
    end
end

app/views/shop_detail_types/_form.html.erb
<%= form_for(@shop_detail_type) do |f| %>
  <% if @shop_detail_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shop_detail_type.errors.count, "error") %> prohibited this shop from being saved:</h2>

      <ul>
      <% @shop_detail_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    カテゴリー名<br>
    <%= f.select :shop_category_id, @shop_category.map{|t|[t.type_name, t.id]} %>
  </div>
   <div class="field">
    詳細な項目<br>
    <%= f.text_field :detail_tag_name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shop_detail_types/edit.html.erb
<h1>Editing company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/shop_detail_types/index.html.erb
<h1>お店の特徴</h1>

<table class="table">
  <thead>
    <tr>
      <th>No.</th>
      <th>カテゴリー</th>
      <th>詳細な項目</th>
      <th colspan="3">編集</th>
    </tr>
  </thead>

  <tbody>
    <% @shop_detail_types.each do |shop_detail_type| %>
      <tr>
	<td><%= shop_detail_type.id%></td>
	<td><%= @hash[shop_detail_type.shop_category_id] %></td>
        <td><%= shop_detail_type.detail_tag_name %></td>
        <td><%= link_to 'Show', shop_detail_type %></td>
        <td><%= link_to 'Edit', edit_shop_detail_type_path(shop_detail_type) %></td>
        <td><%= link_to 'Destroy', shop_detail_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shop_Detail_Type', new_shop_detail_type_path %>

app/views/shop_detail_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>詳細な項目</strong>
  <%= @shop_detail_type.detail_tag_name %>
</p>

<%= link_to 'Edit', edit_shop_detail_type_path(@shop_detail_type) %> |
<%= link_to 'Back', shop_detail_types_path %>